/**
 * @file
 * @ingroup mcu mcu_adc
 */


#include "../mcu_adc.h"


namespace mcu {
/// @addtogroup mcu_adc
/// @{


///
///
///
void initAdcChannels(emb::Array<detail::AdcChannelImpl, ADC_CHANNEL_COUNT>& channels)
{
	channels[ADC_CURRENT_PHASE_U] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN0, ADC_SOC_NUMBER0, ADC_TRIGGER_SW_ONLY);
	channels[ADC_CURRENT_PHASE_V] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN1, ADC_SOC_NUMBER1, ADC_TRIGGER_SW_ONLY);
	channels[ADC_CURRENT_PHASE_W] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN2, ADC_SOC_NUMBER2, ADC_TRIGGER_SW_ONLY);
	channels[ADC_CURRENT_PHASE_X] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN5, ADC_SOC_NUMBER3, ADC_TRIGGER_SW_ONLY);
	channels[ADC_CURRENT_PHASE_Y] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN4, ADC_SOC_NUMBER4, ADC_TRIGGER_SW_ONLY);
	channels[ADC_CURRENT_PHASE_Z] = detail::AdcChannelImpl(
			ADCB_BASE, ADCBRESULT_BASE, ADC_CH_ADCIN3, ADC_SOC_NUMBER5, ADC_TRIGGER_SW_ONLY);

	channels[ADC_VOLTAGE_DC] = detail::AdcChannelImpl(
			ADCD_BASE, ADCDRESULT_BASE, ADC_CH_ADCIN0, ADC_SOC_NUMBER0, ADC_TRIGGER_SW_ONLY);

	channels[ADC_TEMPERATURE_PHASE_U] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN14, ADC_SOC_NUMBER0, ADC_TRIGGER_SW_ONLY);
	channels[ADC_TEMPERATURE_PHASE_V] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN15, ADC_SOC_NUMBER1, ADC_TRIGGER_SW_ONLY);
	channels[ADC_TEMPERATURE_PHASE_W] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN2, ADC_SOC_NUMBER2, ADC_TRIGGER_SW_ONLY);
	channels[ADC_TEMPERATURE_PHASE_X] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN3, ADC_SOC_NUMBER3, ADC_TRIGGER_SW_ONLY);
	channels[ADC_TEMPERATURE_PHASE_Y] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN4, ADC_SOC_NUMBER4, ADC_TRIGGER_SW_ONLY);
	channels[ADC_TEMPERATURE_PHASE_Z] = detail::AdcChannelImpl(
			ADCC_BASE, ADCCRESULT_BASE, ADC_CH_ADCIN5, ADC_SOC_NUMBER5, ADC_TRIGGER_SW_ONLY);

	channels[ADC_TEMPERATURE_CASE] = detail::AdcChannelImpl(
			ADCD_BASE, ADCDRESULT_BASE, ADC_CH_ADCIN1, ADC_SOC_NUMBER1, ADC_TRIGGER_SW_ONLY);
}


///
///
///
void initAdcIrqs(emb::Array<detail::AdcIrqImpl, ADC_IRQ_COUNT>& irqs)
{
	irqs[ADC_IRQ_CURRENT_UVW] = detail::AdcIrqImpl(
			ADCB_BASE, ADC_INT_NUMBER2, ADC_SOC_NUMBER2, INT_ADCB2);
	irqs[ADC_IRQ_CURRENT_XYZ] = detail::AdcIrqImpl(
			ADCB_BASE, ADC_INT_NUMBER3, ADC_SOC_NUMBER5, INT_ADCB3);

	irqs[ADC_IRQ_VOLTAGE_DC] = detail::AdcIrqImpl(
			ADCD_BASE, ADC_INT_NUMBER2, ADC_SOC_NUMBER0, INT_ADCD2);

	irqs[ADC_IRQ_TEMPERATURE_UVW] = detail::AdcIrqImpl(
			ADCC_BASE, ADC_INT_NUMBER2, ADC_SOC_NUMBER2, INT_ADCC2);
	irqs[ADC_IRQ_TEMPERATURE_XYZ] = detail::AdcIrqImpl(
			ADCC_BASE, ADC_INT_NUMBER3, ADC_SOC_NUMBER5, INT_ADCC3);

	irqs[ADC_IRQ_TEMPERATURE_CASE] = detail::AdcIrqImpl(
			ADCD_BASE, ADC_INT_NUMBER3, ADC_SOC_NUMBER1, INT_ADCD3);
}


/// @}
} // namespace mcu


